"""
create_overlay_gif.py
---------------------
Reads sequences of JPEG images generated by vis_pseudo_mask.py, stacks the 
attention heatmaps and masks onto the RGB frames, and exports them as GIFs.

Usage:
    python create_overlay_gif.py --vis_dir /path/to/your/vis_dir
"""

import os
import argparse
import numpy as np
from PIL import Image, ImageDraw
from pathlib import Path
from tqdm import tqdm


def load_image_sequence(dir_path: Path, target_frames: int = 16) -> np.ndarray:
    """
    Loads a folder of sequentially named JPEGs (e.g., 000.jpg, 001.jpg) 
    into a (T, H, W, 3) numpy array and forces it to `target_frames`.
    """
    if not dir_path.exists():
        return None
        
    img_files = sorted(dir_path.glob("*.jpg"))
    if not img_files:
        return None
        
    frames = [np.array(Image.open(f).convert('RGB')) for f in img_files]
    frames = np.stack(frames)
    
    # Force exactly 16 frames (downsample or upsample as needed to stay synced)
    if len(frames) != target_frames:
        indices = np.linspace(0, len(frames) - 1, target_frames).astype(int)
        frames = frames[indices]
        
    return frames


def save_as_gif(frames_np: np.ndarray, path: Path, duration: int = 150):
    """Saves a (T, H, W, 3) numpy array as a looping GIF."""
    os.makedirs(path.parent, exist_ok=True)
    imgs = [Image.fromarray(f) for f in frames_np]
    imgs[0].save(
        path,
        save_all=True,
        append_images=imgs[1:],
        optimize=True,
        duration=duration,
        loop=0,
    )


def blend_heatmap(base: np.ndarray, overlay: np.ndarray, alpha: float = 0.5) -> np.ndarray:
    """Blends a heatmap onto the base frame."""
    if overlay is None or base is None:
        return base
        
    # Identify non-black pixels in the heatmap
    active = (np.sum(overlay, axis=-1, keepdims=True) > 15).astype(np.float32)
    
    base_f = base.astype(np.float32)
    over_f = overlay.astype(np.float32)
    
    blended = base_f * (1.0 - active * alpha) + over_f * (active * alpha)
    return blended.clip(0, 255).astype(np.uint8)


def blend_mask(base: np.ndarray, overlay: np.ndarray, color: tuple, alpha: float = 0.75) -> np.ndarray:
    """
    Uses a Luminance Tint to perfectly preserve the original texture/shadows 
    while applying a strong color overlay.
    """
    if overlay is None or base is None:
        return base
        
    # Identify where the mask exists (sum of RGB > 15 ignores pure black backgrounds)
    active = (np.sum(overlay, axis=-1, keepdims=True) > 15).astype(np.float32)
    
    base_f = base.astype(np.float32)
    color_arr = np.array(color, dtype=np.float32)
    
    # 1. Calculate grayscale luminance of the base image to find shadows/highlights
    luminance = np.sum(base_f * np.array([0.2989, 0.5870, 0.1140]), axis=-1, keepdims=True)
    
    # 2. Map the luminance to the target color (Boosted slightly so the color pops)
    tinted = np.clip((luminance / 200.0), 0, 1.0) * color_arr
    
    # 3. Blend the original base with the new texture-preserved tint
    blended = base_f * (1.0 - active * alpha) + tinted * (active * alpha)
    
    return blended.clip(0, 255).astype(np.uint8)


def apply_label(frames: np.ndarray, text: str) -> np.ndarray:
    """Draws a clean black background label over the top-left corner."""
    labeled_frames = frames.copy()
    for t in range(len(labeled_frames)):
        img = Image.fromarray(labeled_frames[t])
        draw = ImageDraw.Draw(img)
        draw.rectangle([0, 0, len(text) * 7 + 10, 16], fill=(0, 0, 0))
        draw.text((2, 1), text, fill=(255, 255, 255))
        labeled_frames[t] = np.array(img)
    return labeled_frames


def main():
    parser = argparse.ArgumentParser(description="Convert JPEG Sequences to Overlay GIFs")
    parser.add_argument('--vis_dir', type=str, required=True, 
                        help="Root directory containing the 'rgb', 'attn_before', etc. folders")
    args = parser.parse_args()
    
    vis_dir = Path(args.vis_dir)
    
    out_before_dir = vis_dir / "gif_overlay_before"
    out_after_dir  = vis_dir / "gif_overlay_after"
    
    rgb_dir = vis_dir / "rgb"
    if not rgb_dir.exists():
        print(f"Error: Could not find base RGB directory at {rgb_dir}")
        return
        
    # Find all sample subdirectories (e.g., '00001_c:z1-z2') inside the rgb folder
    sample_dirs = sorted([d for d in rgb_dir.iterdir() if d.is_dir()])
    print(f"Found {len(sample_dirs)} samples to composite in {vis_dir}...")
    
    RED = (255, 50, 50)
    
    for rgb_sample_dir in tqdm(sample_dirs, desc="Creating GIFs"):
        name = rgb_sample_dir.name
        
        # ── 1. Load Assets from JPEG folders ─────────────────────────────────
        rgb_frames  = load_image_sequence(rgb_sample_dir)
        attn_before = load_image_sequence(vis_dir / "attn_before" / name)
        init_mask   = load_image_sequence(vis_dir / "initial_mask" / name)
        
        inpainted_path = vis_dir / "rgb" / name
        rgb_after_base = load_image_sequence(inpainted_path) if inpainted_path.exists() else rgb_frames
        
        attn_diff   = load_image_sequence(vis_dir / "attn_diff" / name)
        ref_mask    = load_image_sequence(vis_dir / "refined_mask" / name)
        
        # ── 2. Composite 'Before' Panel ──────────────────────────────────────
        comp_before = blend_heatmap(rgb_frames, attn_before, alpha=0.5)
        comp_before = blend_mask(comp_before, init_mask, color=RED, alpha=0.75)
        
        if comp_before is not None:
            comp_before = apply_label(comp_before, "Before: Initial")
            save_as_gif(comp_before, out_before_dir / f"{name}.gif")
            
        # ── 3. Composite 'After' Panel (if refinement assets exist) ──────────
        if attn_diff is not None and ref_mask is not None:
            comp_after = blend_heatmap(rgb_after_base, attn_diff, alpha=0.5)
            comp_after = blend_mask(comp_after, ref_mask, color=RED, alpha=0.75)
            
            comp_after = apply_label(comp_after, "After: Refined")
            save_as_gif(comp_after, out_after_dir / f"{name}.gif")


if __name__ == "__main__":
    main()